### ISSUE TITLE
Set device intensity by settings.conf

### ISSUE THREAD

**Issue by kauanmocelin** [YoRyan/nuxhash#114]
Set device intensity is a core feature for me, otherwise my gpu working very hot.

After studying a while Excavator API, I did Excavator config by hand(subscribe, algorithm, workers, device) and run it with success. But do this every time is very painful, so is there any way to pass device intensity by settings.conf, "args = " maybe?

**Comment by kauanmocelin** [comment]
I tuned my gpu to work properly on mining.

**Comment by cprn** [comment]
Can you share how exactly?

Edit, because I didn't want to notify everyone: I meant "what requests exactly have you sent to which end-point of the excavator API" so I could maybe try to implement them in a PR to this repository, not "how do I overclock a GPU"... But it's irrelevant now, I'm not involved any more.

**Comment by kauanmocelin** [comment]
@cprn use [this settings](https://www.nicehash.com/blog/post/nvidia-and-amd-graphics-card-oc-settings-for-mining) accordly your gpu.
To overclock your gpu depends your OS(for Windows use MSI Afterburner), so at a quick search on youtube you find it.
